### ISSUE TITLE
ImportError: cannot import name 'Log10'

### ISSUE THREAD

**Issue by bhishanpdl** [HunterMcGushion/hyperparameter_hunter#216]
I created a brand new conda environment just to install hyperparameter-hunter and installed few packages. 
Then, when I try to run one of the example eg. `xgboost_examples/classification.py` it gives me following error:

# Info
```
Macos catalina, miniconda, python3.8
date: Dec 29, 2020


pip freeze
hyperparameter-hunter==3.0.0
scikit-learn==0.24.0
scikit-optimize==0.8.1
scipy==1.5.4
```

# Error
```bash
$ python classification.py
Traceback (most recent call last):
  File "classification.py", line 1, in <module>
    from hyperparameter_hunter import Environment, CVExperiment
  File "/Users/poudel/opt/miniconda3/envs/hh/lib/python3.8/site-packages/hyperparameter_hunter/__init__.py", line 16, in <module>
    from .importer import hook_keras_layer, hook_keras_initializers
  File "/Users/poudel/opt/miniconda3/envs/hh/lib/python3.8/site-packages/hyperparameter_hunter/importer.py", line 13, in <module>
    from hyperparameter_hunter.tracers import ArgumentTracer, LocationTracer
  File "/Users/poudel/opt/miniconda3/envs/hh/lib/python3.8/site-packages/hyperparameter_hunter/tracers.py", line 18, in <module>
    from hyperparameter_hunter.space.dimensions import Real, Integer, Categorical
  File "/Users/poudel/opt/miniconda3/envs/hh/lib/python3.8/site-packages/hyperparameter_hunter/space/dimensions.py", line 40, in <module>
    from skopt.space.transformers import CategoricalEncoder, Normalize, Identity, Log10, Pipeline
ImportError: cannot import name 'Log10' from 'skopt.space.transformers' (/Users/poudel/opt/miniconda3/envs/hh/lib/python3.8/site-packages/skopt/space/transformers.py)
```

# Installed packages
```bash
appnope @ file:///opt/concourse/worker/volumes/live/5f13e5b3-5355-4541-5fc3-f08850c73cf9/volume/appnope_1606859448618/work
argon2-cffi @ file:///opt/concourse/worker/volumes/live/59af29ac-4890-416e-7ab7-794f8d6f7ecd/volume/argon2-cffi_1596828548321/work
async-generator==1.10
attrs @ file:///tmp/build/80754af9/attrs_1604765588209/work
backcall==0.2.0
bleach @ file:///tmp/build/80754af9/bleach_1600439572647/work
catboost @ https://pypi.org/packages/cp38/c/catboost/catboost-0.24.4-cp38-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl
category-encoders @ file:///home/conda/feedstock_root/build_artifacts/category_encoders_1588199510095/work/dist
certifi==2020.12.5
cffi @ file:///opt/concourse/worker/volumes/live/730e9a28-66f9-4e03-51ad-252ec8e40d81/volume/cffi_1606255126408/work
cycler==0.10.0
decorator==4.4.2
defusedxml==0.6.0
dill==0.3.3
entrypoints==0.3
hyperparameter-hunter==3.0.0
imbalanced-learn @ file:///home/conda/feedstock_root/build_artifacts/imbalanced-learn_1591716883293/work
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
ipykernel @ file:///opt/concourse/worker/volumes/live/88f541d3-5a27-498f-7391-f2e50ca36560/volume/ipykernel_1596206680118/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///opt/concourse/worker/volumes/live/26969e8f-c9f7-42dc-6ffb-b3effd424c49/volume/ipython_1604101242376/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
jedi==0.17.0
Jinja2==2.11.2
joblib @ file:///home/conda/feedstock_root/build_artifacts/joblib_1607956439537/work
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1601311786391/work
jupyter-core @ file:///opt/concourse/worker/volumes/live/e8302867-5dbe-440b-7a37-f61bacc38ed8/volume/jupyter_core_1606148993907/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
kiwisolver @ file:///opt/concourse/worker/volumes/live/b8936fa6-0e4b-47e7-4fb4-e02dbd4505ee/volume/kiwisolver_1604014598721/work
lightgbm @ file:///Users/runner/miniforge3/conda-bld/lightgbm_1607450056098/work
MarkupSafe @ file:///opt/concourse/worker/volumes/live/cb778296-98db-45ad-411e-6f726e102dc3/volume/markupsafe_1594371638608/work
matplotlib @ file:///Users/runner/miniforge3/conda-bld/matplotlib-base_1594091691585/work
mistune @ file:///opt/concourse/worker/volumes/live/95802d64-d39c-491b-74ce-b9326880ca54/volume/mistune_1594373201816/work
mlxtend @ file:///home/conda/feedstock_root/build_artifacts/mlxtend_1606368531479/work
nb-conda-kernels @ file:///opt/concourse/worker/volumes/live/82c137e0-23e6-475b-7bb1-19e036b0f8ea/volume/nb_conda_kernels_1606775964383/work
nbclient @ file:///tmp/build/80754af9/nbclient_1602783176460/work
nbconvert @ file:///opt/concourse/worker/volumes/live/2b9c1d93-d0fd-432f-7d93-66c93d81b614/volume/nbconvert_1601914875037/work
nbformat @ file:///tmp/build/80754af9/nbformat_1602783287752/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1606153767164/work
notebook @ file:///opt/concourse/worker/volumes/live/d85c0794-1357-4fff-61be-761a5e60b85b/volume/notebook_1608835566278/work
numpy @ file:///Users/runner/miniforge3/conda-bld/numpy_1607937594810/work
packaging @ file:///tmp/build/80754af9/packaging_1607971725249/work
pandas==1.2.0
pandocfilters @ file:///opt/concourse/worker/volumes/live/c330e404-216d-466b-5327-8ce8fe854d3a/volume/pandocfilters_1605120442288/work
parso @ file:///tmp/build/80754af9/parso_1607623074025/work
patsy==0.5.1
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
prometheus-client @ file:///tmp/build/80754af9/prometheus_client_1606344362066/work
prompt-toolkit @ file:///tmp/build/80754af9/prompt-toolkit_1602688806899/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1605560620615/work/dist/ptyprocess-0.6.0-py2.py3-none-any.whl
pyaml==20.4.0
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
Pygments @ file:///tmp/build/80754af9/pygments_1607368905949/work
pyparsing==2.4.7
pyrsistent @ file:///opt/concourse/worker/volumes/live/ff11f3f0-615b-4508-471d-4d9f19fa6657/volume/pyrsistent_1600141727281/work
python-dateutil==2.8.1
pytz @ file:///home/conda/feedstock_root/build_artifacts/pytz_1608904108784/work
PyYAML==5.3.1
pyzmq==20.0.0
scikit-learn==0.24.0
scikit-optimize==0.8.1
scikit-plot==0.3.7
scipy==1.5.4
seaborn @ file:///home/conda/feedstock_root/build_artifacts/seaborn-base_1608544589436/work
Send2Trash @ file:///tmp/build/80754af9/send2trash_1607525499227/work
simplejson==3.17.2
six @ file:///opt/concourse/worker/volumes/live/5b31cb27-1e37-4ca5-6e9f-86246eb206d2/volume/six_1605205320872/work
statsmodels @ file:///Users/runner/miniforge3/conda-bld/statsmodels_1605985682916/work
terminado==0.9.1
testpath==0.4.4
threadpoolctl==2.1.0
tornado @ file:///opt/concourse/worker/volumes/live/05341796-4198-4ded-4a9a-332fde3cdfd1/volume/tornado_1606942323372/work
traitlets @ file:///tmp/build/80754af9/traitlets_1602787416690/work
watermark @ file:///home/conda/feedstock_root/build_artifacts/watermark_1606258612096/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
wrapt==1.12.1
xgboost==1.3.0
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work

```

**Comment by astro-jingtao** [comment]
The 'Log10' in 'skopt' chaged to 'LogN'.
Replace all 'Log10' with 'LogN' in hyperparameter_hunter/space/dimensions.py will fix this problem.
